CREATE TABLE IF NOT EXISTS Products (
  ID                INT  AUTO_INCREMENT  PRIMARY KEY,
  PRODUCT_NAME      VARCHAR(100) NOT NULL,
  PRODUCT_PRICE     INT NOT NULL,
  PRODUCT_ARTICLE   VARCHAR(100) NOT NULL,
  PRODUCT_QUANTITY  INT NOT NULL,
  DATE_CREATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);